module.exports = {
  extends: ["stylelint-prettier/recommended"],
  plugins: ["stylelint-prettier", "stylelint-order"],
  customSyntax: "postcss-less",
  rules: {
    "prettier/prettier": true,
    "order/properties-order": [
      [
        "content",
        "position",
        "inset",
        "top",
        "right",
        "bottom",
        "left",
        "z-index",
        "display",
        "flex",
        "grid",
        "clear",
        "float",
        "overflow",
        "overflow-x",
        "overflow-y",
        "width",
        "min-width",
        "max-width",
        "height",
        "min-height",
        "max-height",
        "padding",
        "padding-top",
        "padding-right",
        "padding-bottom",
        "padding-left",
        "margin",
        "margin-top",
        "margin-right",
        "margin-bottom",
        "margin-left",
        "font",
        "font-family",
        "font-style",
        "font-size",
        "font-weight",
        "color",
        "text-align",
        "text-transform",
        "text-decoration",
        "text-indent",
        "line-height",
        "list-style",
        "vertical-align",
        "background",
        "background-image",
        "background-color",
        "background-clip",
        "background-position",
        "background-repeat",
        "background-attachment",
        "border",
        "border-color",
        "border-left",
        "border-right",
        "border-top",
        "border-bottom",
        "border-radius",
        "box-shadow",
        "box-sizing",
      ],
    ],
  },
};
